<?php
ini_set('display_errors', true);
require_once "action.php";


?>

<html>
<head>
    <link rel="stylesheet" href="berichtsheft_css.css">

</head>


<body>


<h2>test</h2>

<?php
// connect to database
$con = createConnection();


// how many results you want per page
$results_per_page = 10;


// find out the number of results stored in database
$sql = 'SELECT * FROM tbl_Berichte';
$result = mysqli_query($con, $sql);
$number_of_results = mysqli_num_rows($result);


// number of total pages available
$number_of_pages = ceil($number_of_results / $results_per_page);


// which page number visitor is currently on
if (!isset($_GET['page'])) {
    $page = 1;
} else {
    $page = $_GET['page'];
}


// determine the sql LIMIT starting number for the results on the displaying page
$this_page_first_result = ($page - 1) * $results_per_page;


// selected results are displayed on page in table
$sql = 'SELECT * FROM tbl_Berichte ORDER BY Datum DESC LIMIT ' . $this_page_first_result . ',' . $results_per_page;
$result = mysqli_query($con, $sql);
echo "<table border='1px solid black;'class='one'>";
echo "<tr><th> Mitarbeiter ID</th><th> Datum </th><th>Bericht</th> <th>actions</th></tr> ";
while ($row = mysqli_fetch_array($result)) {
    echo "<tr>
                    <td> " . $row["mitarbeiter_id"] . "</td>
                    <td>" . $row["Datum"] . "</td>
                    <form action='action.php' method='post'>
                      <td><input type='textarea' name='Bericht_tbl' value= '" . $row["Bericht"] . "'> </td> <td>

                          <input type='hidden' name='id' value='" . $row["id"] . "'>
                          <input type='submit' name='action' value='Update' >
                          <input type='submit' name='action' value='Löschen'>
                    </form>
                    </td>
                </tr>";

}

?>

<table class="two">
    <tr>

        <td class="<?php if ($page >= $number_of_pages) {echo 'disabled';} ?>">
            <a href="<?php if ($page >= $number_of_pages) {echo '#';} else {echo "?page=" . ($page + 1);} ?>">Next</a>
        <td class="<?php if ($page <= 1) {echo 'disabled';} ?>">
            <a href="<?php if ($page <= 1) {echo '#';} else {echo "?page=" . ($page - 1);} ?>">Back</a>
        <td><a href="?page=1">First</a></td>
        <td><a href="?page=<?php echo $number_of_pages; ?>">Last</a></td>
    </tr>
</table>
</form>
<ul class="index">
    <li><a href="Mainpage.phtml">Zur Hauptseite zurück</a></li>
    <li><a href="new_bericht.phtml">Einen neuen Bericht schreiben</a></li>
    <li><a href="New_azubi.phtml">Einen neuen Azubi/Mitarbeiter anlegen</a></li>
    <li><a href="bericht_suchen.phtml">Einen bestimmten Bericht suchen</a></li>
</ul>

</body>
</html>