<?php
ini_set('display_errors', true);
require_once "action.php"
?>
<html>
<head>
    <link rel="stylesheet" href="berichtsheft_css.css">
    <link rel="stylesheet" media="print" href="print.css">
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
    <link rel="stylesheet" href="/resources/demos/style.css">
    <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
    <script>

        $(function () {

            $("#datepickerFrom").datepicker({ dateFormat: "dd.mm.yy"});
            $("#datepickerTo").datepicker({ dateFormat: "dd.mm.yy"});
        });



    </script>

</head>
<body>
<form action="bericht_drucken.phtml" form="post">
<?php
if (isset($_POST['search'])) {
    $valueToSearchDateTime = new DateTime($_POST['DatumFrom']);
    $valueToSearchToDateTime = new DateTime($_POST['DatumTo']);
    // search in all table columns
    // using concat mysql function
    $query = "SELECT * FROM tbl_Berichte WHERE Datum BETWEEN '" . $valueToSearchDateTime->format('Y-m-d') . "' AND '" . $valueToSearchToDateTime->format('Y-m-d') . "'  ORDER BY Datum ASC ";
    $search_result = filterTable($query);

} else {
    $query = "SELECT * FROM tbl_Berichte";
    $search_result = filterTable($query);
}

// function to connect and execute the query
function filterTable($query)
{
    $connect = createConnection();
    $filter_Result = mysqli_query($connect, $query);
    return $filter_Result;
}
//dropdown functions----------------------------------
$connect = createConnection();
$query1 = "SELECT id FROM tbl_Mitarbeiter";
$result1 = mysqli_query($connect, $query1);

?>
    <p class="header_print">Azubiberichte</p>
</form>
<h2>Bericht suche</h2>
<form action="bericht_suchen.phtml" method="post">

    <p>Von:</p><input type="text" name="DatumFrom" id="datepickerFrom" value="."></p>
    <p>Bis:</p><input type="text" name="DatumTo" id="datepickerTo" value="."></p>
    <p>Welcher Azubi:</p><br>
    <select>
        <?php while($row1 = mysqli_fetch_array($result1)):;?>

            <option value="<?php echo $row1[0];?>"><?php echo $row1[1];?></option>

        <?php endwhile;?>
    </select>

    <br>
    <br>

    <input type="submit" name="search" value="Filter" class="btn-gradient red small"><br><br>
</form>
    <table class="bericht_drucken">

        <?php echo "<tr><th> Mitarbeiter ID</th><th> Datum </th><th>Bericht</th> <th class='not_needed'>actions</th></tr> ";
        while ($row = mysqli_fetch_array($search_result)) {
            echo "<tr>
                    <td> " . $row["mitarbeiter_id"] . "</td>
                    <td>" . $row["Datum"] . "</td>
                    <form action='action.php' method='post'>
                      <td><input type='textarea' name='Bericht_tbl' value= '" . $row["Bericht"] . "'> </td> 
                      <td class='not_needed'>
                          <input type='hidden' name='id' value='" . $row["id"] . "'>
                          <input type='submit' name='action' value='Update' class='btn-gradient red small'>
                          <input type='submit' name='action' value='Löschen' class='btn-gradient red small'>
                    </form>
                    </td>
                </tr>";


        }

        ?>
</table>

    <button onclick="myFunction()" class="print_btn">Print this page</button>

    <script>
        function myFunction() {
            window.print();
        }
    </script>
<p class="signed">Unterschrift des Azubis:_______________________________</p>
<p class="signed">Unterschrift des Auaszubildenen :_______________________________</p>
</form>

<ul class="index">
    <li><a href="Mainpage.phtml">Zur Hauptseite zurück</a></li>
    <li><a href="new_bericht.phtml">Einen neuen Bericht schreiben</a></li>
    <li><a href="all_berichte.phtml">Überblick über alle Berichte</a></li>
    <li><a href="New_azubi.phtml">Einen neuen Azubi/Mitarbeiter anlegen</a></li>


</ul>
</body>
</html>
