<?php
ini_set('display_errors', true);
require_once "action.php"
?>
<html>
<head>
    <link rel="stylesheet" href="berichtsheft_css.css">
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
    <link rel="stylesheet" href="/resources/demos/style.css">
    <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
    <script>
        $(function () {
            $("#datepicker").datepicker();
            $("#format").on("change", function () {
                $("#datepicker").datepicker("option", "dateFormat", $(this).val());
            });
        });
    </script>

</head>
<body>
<?php

if (isset($_POST['search'])) {
    $valueToSearch = $_POST['Datum'];
    // search in all table columns
    // using concat mysql function
    $query = "SELECT * FROM tbl_Berichte WHERE CONCAT(`Datum`) LIKE '" . $valueToSearch . "'";
    $search_result = filterTable($query);

} else {
    $query = "SELECT * FROM tbl_Berichte";
    $search_result = filterTable($query);
}

// function to connect and execute the query
function filterTable($query)
{
    $connect = mysqli_connect("localhost", "Pascal", "Pascalstanley03", "Berichtsheft");
    $filter_Result = mysqli_query($connect, $query);
    return $filter_Result;
}
createConnection();
?>
<h2>Bericht suche</h2>
<form action="bericht_suchen.phtml" method="post">

    Datum :<br><input type="text" name="Datum" id="datepicker" value=".">
    <br><br>
    <p>Format options:<br>
        <select id="format">
            <option value="mm/dd/yy">Default - mm/dd/yy</option>
            <option value="yy-mm-dd">ISO 8601 - yy-mm-dd</option>
            <option value="d M, y">Short - d M, y</option>
            <option value="d MM, y">Medium - d MM, y</option>
            <option value="DD, d MM, yy">Full - DD, d MM, yy</option>
            <option value="&apos;day&apos; d &apos;of&apos; MM &apos;in the year&apos; yy">With text - 'day' d 'of' MM
                'in the year' yy
            </option>
        </select>
    </p>
    <input type="submit" name="search" value="Filter"><br><br>
    <table>
        <tr>
            <th>Mitarbeiter</th>
            <th>Datum</th>
            <th>Bericht</th>
            <th>Funktion</th>
        </tr>
        <?php while ($row = mysqli_fetch_array($search_result)): ?>
        <tr>
            <td><?php echo $row['mitarbeiter_id']; ?></td>
            <td><?php echo $row['Datum']; ?></td>
            <td><input type='textarea' name='Bericht_tbl' value= <?php echo $row['Bericht']; ?>></td>
            <td>
                <form action="action.php" method="post">
                <input type='hidden' name='id' value=<?php echo $row['id']; ?>>
                <input type='submit' name='action' value='Update'>
                <input type='submit' name='action' value='Löschen'>
                </form>
            </td>

</tr>
<?php endwhile;?>
</table>


</form>

<ul class="index">
    <li><a href="Mainpage.phtml">Zur Hauptseite zurück</a></li>
    <li><a href="new_bericht.phtml">Einen neuen Bericht schreiben</a></li>
    <li><a href="all_berichte.phtml">Überblick über alle Berichte</a></li>
    <li><a href="New_azubi.phtml">Einen neuen Azubi/Mitarbeiter anlegen</a></li>

</ul>
</body>
</html>
