<?php
ini_set('display_errors', true);
require_once "action.php"
?>
<html>
<head>
    <link rel="stylesheet" href="berichtsheft_css.css">
    <link rel="stylesheet" media="print" href="print.css">
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
    <link rel="stylesheet" href="/resources/demos/style.css">
    <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
    <script>
        $(function () {
            $("#datepicker").datepicker();
            $("#format").on("change", function () {
                $("#datepicker").datepicker("option", "dateFormat", $(this).val());
            });
        });
        $(function () {
            $("#datepickerTwo").datepicker();
            $("#format").on("change", function () {
                $("#datepickerTwo").datepicker("option", "dateFormat", $(this).val());
            });
        });
    </script>

</head>
<body>
<form action="bericht_drucken.phtml" form="post">
<?php

if (isset($_POST['search'])) {
    $valueToSearch = $_POST['Datum'];
    $valueToSearchTwo = $_POST['DatumTwo'];
    // search in all table columns
    // using concat mysql function
    $query = "SELECT * FROM tbl_Berichte WHERE Datum BETWEEN '" . $valueToSearch . "' AND '" . $valueToSearchTwo . "' ORDER BY Datum DESC ";
    $search_result = filterTable($query);

} else {
    $query = "SELECT * FROM tbl_Berichte";
    $search_result = filterTable($query);
}

// function to connect and execute the query
function filterTable($query)
{
    $connect = mysqli_connect("localhost", "Pascal", "Pascalstanley03", "Berichtsheft");
    $filter_Result = mysqli_query($connect, $query);
    return $filter_Result;
}
createConnection();
?>
</form>
<h2>Bericht suche</h2>
<form action="bericht_suchen.phtml" method="post">

    <p>Von:</p><input type="text" name="Datum" id="datepicker" value="."><br><br>
    <p>Bis:</p><input type="text" name="DatumTwo" id="datepickerTwo" value=".">
    <br>
    <p>Format options:<br>
        <select id="format">
            <option value="mm/dd/yy">Default - mm/dd/yy</option>
            <option value="yy-mm-dd">ISO 8601 - yy-mm-dd</option>
            <option value="d M, y">Short - d M, y</option>
            <option value="d MM, y">Medium - d MM, y</option>
            <option value="DD, d MM, yy">Full - DD, d MM, yy</option>
            <option value="&apos;day&apos; d &apos;of&apos; MM &apos;in the year&apos; yy">With text - 'day' d 'of' MM
                'in the year' yy
            </option>
        </select>
    </p>
    <br>

    </p>
    <input type="submit" name="search" value="Filter" class="btn-gradient red small"><br><br>
    <table class="bericht_drucken">

        <?php echo "<tr><th> Mitarbeiter ID</th><th> Datum </th><th>Bericht</th> <th class='not_needed'>actions</th></tr> ";
        while ($row = mysqli_fetch_array($search_result)) {
            echo "<tr>
                    <td> " . $row["mitarbeiter_id"] . "</td>
                    <td>" . $row["Datum"] . "</td>
                    <form action='action.php' method='post'>
                      <td><input type='textarea' name='Bericht_tbl' value= '" . $row["Bericht"] . "'> </td> 
                      <td class='not_needed'>
                          <input type='hidden' name='id' value='" . $row["id"] . "'>
                          <input type='submit' name='action' value='Update' class='btn-gradient red small'>
                          <input type='submit' name='action' value='Löschen' class='btn-gradient red small'>
                    </form>
                    </td>
                </tr>";


        }

        ?>
</table>

    <button onclick="myFunction()" class="print_btn">Print this page</button>

    <script>
        function myFunction() {
            window.print();
        }
    </script>


</form>

<ul class="index">
    <li><a href="Mainpage.phtml">Zur Hauptseite zurück</a></li>
    <li><a href="new_bericht.phtml">Einen neuen Bericht schreiben</a></li>
    <li><a href="all_berichte.phtml">Überblick über alle Berichte</a></li>
    <li><a href="New_azubi.phtml">Einen neuen Azubi/Mitarbeiter anlegen</a></li>


</ul>
</body>
</html>
