<html>
	<head></head>
    <link rel="stylesheet" href="berichtsheft_css.css">

    <body>
    <?php


    ?>



    <h2>Azubi Berichtsheft</h2>


<form action="action.php" method="post">

    Vorname: <br><input type="text" name="Vorname">
    <br><br>
    Nachname:<br><input type="text" name="Nachname">
    <br><br>
    Datum:<br><input type="text" name="Datum">
    <br><br>
    Mitarbeitder ID:<br><input type="text" name="ma_id">
    <br><br>
    Bericht: <br><textarea name="Bericht" rows="5" cols="40"></textarea>
    <br><br>
    <input type="submit" name="submit" value="Speichern">

</form>




    </body>
</html>
