<?php
ini_set('display_errors', true);
require_once "action.php"
?>
<html >
<style>

</style>
<head>
    <link rel="stylesheet" href="berichtsheft_css.css">

</head>
<body>
        <h2>Mainpage</h2>


        <ul>
            <li><a href="new_bericht.phtml">Einen neuen Bericht schreiben</a></li>
            <li><a href="all_berichte.phtml">Überblick über alle Berichte</a></li>
            <li><a href="New_azubi.phtml">Einen neuen Azubi/Mitarbeiter anlegen</a></li>
        </ul>
</body>
</html>
