<?php
ini_set('display_errors', true);
require_once "action.php"
?>
<html>
<head>
    <link rel="stylesheet" href="berichtsheft_css.css">
</head>
<body>


<h2>Azubi Berichtsheft</h2>

<form action="action.php" method="post">
    Vorname: <br><input type="text" name="Vorname">
    <br><br>
    Nachname:<br><input type="text" name="Nachname">
    <br><br>
    Datum (JJJJ.MM.TT):<br><input type="text" name="Datum">
    <br><br>

    Bericht: <br><textarea name="Bericht" rows="5" cols="40"></textarea>
    <br><br>
    <input type="submit" name="action" value="Speichern">
</form>


<h2>Azubi Berichte</h2>


<?php
echo getBerichtsheftEinträgeAsTable();

?>


</body>
</html>
