<?php
ini_set('display_errors', true);
require_once "action.php"
?>
<html>
<style>

</style>
<head>
    <link rel="stylesheet" href="berichtsheft_css.css">

    <h2>Mainpage</h2>
    <ul class="index">
        <li><a href="Mainpage.phtml">Zur Hauptseite zurück</a></li>
        <li><a href="new_bericht.phtml">Einen neuen Bericht schreiben</a></li>
        <li><a href="New_azubi.phtml">Einen neuen Azubi/Mitarbeiter anlegen</a></li>
        <li><a href="all_berichte.phtml">Überblick über alle Berichte</a></li>
        <li><a href="bericht_suchen.phtml">Einen bestimmten Bericht suchen</a></li>
    </ul>

</head>
<body>

</body>
</html>
