<?php
ini_set('display_errors', true);
require_once "action.php"
?>
<html>
<head>
    <link rel="stylesheet" href="berichtsheft_css.css">
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
    <link rel="stylesheet" href="/resources/demos/style.css">
    <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
    <script>
        $(function () {

            $("#datepicker").datepicker({dateFormat: "dd.mm.yy"});
        });

    </script>

</head>
<body>
<ul class="index">
    <li><a href="Mainpage.phtml">Zur Hauptseite zurück</a></li>
    <li><a href="all_berichte.phtml">Überblick über alle Berichte</a></li>
    <li><a href="New_azubi.phtml">Einen neuen Azubi/Mitarbeiter anlegen</a></li>
    <li><a href="bericht_suchen.phtml">Einen bestimmten Bericht suchen</a></li>

</ul>

<form action="action.php" method="post">


    <h2>Azubi Berichtsheft</h2>

    <div class="newbericht">
        Vorname: <br><input type="text" name="Vorname">
        <br><br>
        Nachname:<br><input type="text" name="Nachname">
        <br><br>
        Datum :<br><input type="text" name="Datum" id="datepicker" value=".">
        <br><br>

        </p>
    </div>

    Bericht: <br><textarea name="Bericht" rows="5" cols="40" class="bericht"></textarea>
    <br><br>
    <input type="submit" name="action" value="Speichern" class="btn">
</form>


</body>
</html>
