<?php
ini_set('display_errors', true);
require_once "action.php"
?>
<html >
<head>
    <link rel="stylesheet" href="berichtsheft_css.css">

</head>
<body>
        <h2>Azubis</h2>

<form action="action.php" method="post">

    Vorname: <br><input type="text" name="VornameMA">
    <br><br>
    Nachname:<br><input type="text" name="NachnameMA">
    <br><br>
    <input type="submit" name="action" value="Anlegen"> <input type="submit" name="action" value="Entfernen"><br><br>


    <ul>
        <li> <a href="Mainpage.phtml">Zur Hauptseite zurück</a></li>
        <li><a href="new_bericht.phtml">Einen neuen Bericht schreiben</a></li>
        <li><a href="all_berichte.phtml">Überblick über alle Berichte</a></li>
    </ul>
</body>
</html>
